-- +goose Up
CREATE TABLE workspace_tasks (
 id BIGINT PRIMARY KEY CHECK(id>0), tenant_id BIGINT NOT NULL CHECK(tenant_id>0), entity_id BIGINT NOT NULL CHECK(entity_id>0), owner_id BIGINT NOT NULL CHECK(owner_id>0), requirement_id BIGINT NULL CHECK(requirement_id IS NULL OR requirement_id>0), parent_id BIGINT NULL CHECK(parent_id IS NULL OR parent_id>0),
 kind VARCHAR(16) NOT NULL DEFAULT 'task' CHECK(kind IN ('task','test','bug')), title VARCHAR(300) NOT NULL CHECK(char_length(title) BETWEEN 1 AND 300), description TEXT NOT NULL DEFAULT '', status VARCHAR(16) NOT NULL CHECK(status IN ('open','in_progress','review','done','cancelled')),
 estimate_ms BIGINT NOT NULL DEFAULT 0 CHECK(estimate_ms>=0), spent_ms BIGINT NOT NULL DEFAULT 0 CHECK(spent_ms>=0), progress INTEGER NOT NULL DEFAULT 0 CHECK(progress BETWEEN 0 AND 100), workflow_run_id BIGINT NULL CHECK(workflow_run_id IS NULL OR workflow_run_id>0), workflow_id BIGINT NULL CHECK(workflow_id IS NULL OR workflow_id>0), project_id BIGINT NULL CHECK(project_id IS NULL OR project_id>0), workspace VARCHAR(1024) NOT NULL DEFAULT '', assignee_id BIGINT NULL CHECK(assignee_id IS NULL OR assignee_id>0), channel_id BIGINT NULL CHECK(channel_id IS NULL OR channel_id>0),
 created_at BIGINT NOT NULL CHECK(created_at>0), created_by BIGINT NOT NULL CHECK(created_by>0), updated_at BIGINT NOT NULL CHECK(updated_at>0), updated_by BIGINT NOT NULL CHECK(updated_by>0), deleted_at BIGINT NOT NULL DEFAULT 0 CHECK(deleted_at>=0), deleted_by BIGINT NOT NULL DEFAULT 0 CHECK(deleted_by>=0), version BIGINT NOT NULL DEFAULT 1 CHECK(version>=1),
 CHECK(parent_id IS NULL OR parent_id<>id), CHECK((workflow_id IS NULL AND project_id IS NULL AND workspace='') OR (workflow_id IS NOT NULL AND project_id IS NOT NULL AND char_length(workspace)>0)), CHECK((deleted_at=0 AND deleted_by=0) OR (deleted_at>0 AND deleted_by>0)), CONSTRAINT fk_workspace_task_parent FOREIGN KEY(parent_id) REFERENCES workspace_tasks(id) ON DELETE RESTRICT, CONSTRAINT fk_workspace_task_requirement FOREIGN KEY(requirement_id) REFERENCES workspace_requirements(id) ON DELETE RESTRICT, CONSTRAINT fk_workspace_task_workflow FOREIGN KEY(workflow_id) REFERENCES workflows(id) ON DELETE RESTRICT
);
CREATE INDEX idx_workspace_tasks_scope ON workspace_tasks(tenant_id,entity_id,deleted_at,status,updated_at); CREATE INDEX idx_workspace_tasks_requirement ON workspace_tasks(tenant_id,entity_id,requirement_id,deleted_at); CREATE INDEX idx_workspace_tasks_assignee ON workspace_tasks(tenant_id,entity_id,assignee_id,deleted_at);
-- +goose Down
DROP TABLE IF EXISTS workspace_tasks;
