import type { ReactNode } from "react"

import type { DemoCategory } from "@workspace/ui/components/showcase/component-showcase-config"
import { demoSources } from "./sources.generated"
import { ButtonDemo } from "./button"
import { InputDemo } from "./input"
import { SelectDemo } from "./select"
import { CheckboxDemo } from "./checkbox"
import { SwitchDemo } from "./switch"
import { TextareaDemo } from "./textarea"
import { AutoFormDemo } from "./autoForm"
import { FileUploadDemo } from "./fileUpload"
import { ColorPickerDemo } from "./colorPicker"
import { DatePickerDemo } from "./datePicker"
import { TimePickerDemo } from "./timePicker"
import { TableDemo } from "./table"
import { AutoTableDemo } from "./autoTable"
import { BadgeDemo } from "./badge"
import { SkeletonDemo } from "./skeleton"
import { DialogDemo } from "./dialog"
import { ToastDemo } from "./toast"
import { TooltipDemo } from "./tooltip"
import { PopoverDemo } from "./popover"
import { DropdownMenuDemo } from "./dropdownMenu"
import { TabsDemo } from "./tabs"
import { CardDemo } from "./card"
import { SeparatorDemo } from "./separator"
import { ImageDemo } from "./image"
import { VideoDemo } from "./video"
import { RichTextDemo } from "./richText"
import { CodeDemo } from "./code"
import { AccordionDemo } from "./accordion"
import { AlertDemo } from "./alert"
import { AvatarDemo } from "./avatar"
import { BreadcrumbDemo } from "./breadcrumb"
import { CollapsibleDemo } from "./collapsible"
import { PaginationDemo } from "./pagination"
import { ProgressDemo } from "./progress"
import { RadioGroupDemo } from "./radioGroup"
import { SliderDemo } from "./slider"
import { ScrollAreaDemo } from "./scrollArea"
import { SheetDemo } from "./sheet"
import { ToggleDemo } from "./toggle"
import { MapPickerDemo } from "./mapPicker"
import { LabelDemo } from "./label"
import { ThemeSwitcherDemo } from "./themeSwitcher"
import { LanguageSwitcherDemo } from "./languageSwitcher"
import { TopNavDemo } from "./topNav"
import { SidebarDemo } from "./sidebar"
import { ThemeGalleryDemo } from "./themeGallery"

export interface ComponentDemo {
  id: string
  category: DemoCategory
  component: ReactNode
  /** Actual source code (generated by scripts/extract-demo-source.mjs), used by the "Code" tab */
  source: string
}

function demo(
  id: string,
  category: DemoCategory,
  component: ReactNode
): ComponentDemo {
  return { id, category, component, source: demoSources[id] ?? "" }
}

export const componentDemos: ComponentDemo[] = [
  demo("button", "forms", <ButtonDemo />),
  demo("input", "forms", <InputDemo />),
  demo("select", "forms", <SelectDemo />),
  demo("checkbox", "forms", <CheckboxDemo />),
  demo("switch", "forms", <SwitchDemo />),
  demo("textarea", "forms", <TextareaDemo />),
  demo("autoForm", "automation", <AutoFormDemo />),
  demo("fileUpload", "forms", <FileUploadDemo />),
  demo("colorPicker", "forms", <ColorPickerDemo />),
  demo("datePicker", "forms", <DatePickerDemo />),
  demo("timePicker", "forms", <TimePickerDemo />),
  demo("radioGroup", "forms", <RadioGroupDemo />),
  demo("slider", "forms", <SliderDemo />),
  demo("toggle", "forms", <ToggleDemo />),
  demo("mapPicker", "forms", <MapPickerDemo />),
  demo("table", "data", <TableDemo />),
  demo("autoTable", "automation", <AutoTableDemo />),
  demo("badge", "data", <BadgeDemo />),
  demo("skeleton", "data", <SkeletonDemo />),
  demo("pagination", "data", <PaginationDemo />),
  demo("progress", "data", <ProgressDemo />),
  demo("dialog", "feedback", <DialogDemo />),
  demo("toast", "feedback", <ToastDemo />),
  demo("alert", "feedback", <AlertDemo />),
  demo("tooltip", "overlay", <TooltipDemo />),
  demo("popover", "overlay", <PopoverDemo />),
  demo("dropdownMenu", "overlay", <DropdownMenuDemo />),
  demo("sheet", "overlay", <SheetDemo />),
  demo("tabs", "layout", <TabsDemo />),
  demo("card", "layout", <CardDemo />),
  demo("separator", "layout", <SeparatorDemo />),
  demo("accordion", "layout", <AccordionDemo />),
  demo("collapsible", "layout", <CollapsibleDemo />),
  demo("scrollArea", "layout", <ScrollAreaDemo />),
  demo("image", "media", <ImageDemo />),
  demo("video", "media", <VideoDemo />),
  demo("richText", "media", <RichTextDemo />),
  demo("code", "media", <CodeDemo />),
  demo("breadcrumb", "navigation", <BreadcrumbDemo />),
  demo("avatar", "navigation", <AvatarDemo />),
  demo("topNav", "navigation", <TopNavDemo />),
  demo("sidebar", "navigation", <SidebarDemo />),
  demo("label", "navigation", <LabelDemo />),
  demo("themeSwitcher", "navigation", <ThemeSwitcherDemo />),
  demo("languageSwitcher", "navigation", <LanguageSwitcherDemo />),
  demo("themeGallery", "navigation", <ThemeGalleryDemo />),
]

export function getDemo(id: string): ComponentDemo | undefined {
  return componentDemos.find((d) => d.id === id)
}
