-- +goose Up
CREATE TABLE workspace_defects (
 id BIGINT PRIMARY KEY CHECK(id>0),tenant_id BIGINT NOT NULL CHECK(tenant_id>0),entity_id BIGINT NOT NULL CHECK(entity_id>0),owner_id BIGINT NOT NULL CHECK(owner_id>0),requirement_id BIGINT NULL CHECK(requirement_id IS NULL OR requirement_id>0),task_id BIGINT NULL CHECK(task_id IS NULL OR task_id>0),test_case_id BIGINT NULL CHECK(test_case_id IS NULL OR test_case_id>0),test_run_id BIGINT NULL CHECK(test_run_id IS NULL OR test_run_id>0),
 title VARCHAR(300) NOT NULL CHECK(char_length(title) BETWEEN 1 AND 300),description TEXT NOT NULL,reproduction_steps TEXT NOT NULL,expected_result TEXT NOT NULL,actual_result TEXT NOT NULL,severity VARCHAR(16) NOT NULL CHECK(severity IN ('blocker','critical','major','minor','trivial')),priority VARCHAR(16) NOT NULL CHECK(priority IN ('highest','high','medium','low','lowest')),status VARCHAR(16) NOT NULL CHECK(status IN ('open','triaged','in_progress','resolved','verified','closed','reopened','rejected')),resolution VARCHAR(32) NOT NULL DEFAULT '' CHECK(resolution IN ('','fixed','duplicate','cannot_reproduce','wont_fix','by_design')),resolution_note TEXT NOT NULL,assignee_id BIGINT NULL CHECK(assignee_id IS NULL OR assignee_id>0),
 created_at BIGINT NOT NULL CHECK(created_at>0),created_by BIGINT NOT NULL CHECK(created_by>0),updated_at BIGINT NOT NULL CHECK(updated_at>0),updated_by BIGINT NOT NULL CHECK(updated_by>0),deleted_at BIGINT NOT NULL DEFAULT 0 CHECK(deleted_at>=0),deleted_by BIGINT NOT NULL DEFAULT 0 CHECK(deleted_by>=0),version BIGINT NOT NULL DEFAULT 1 CHECK(version>=1),
 CHECK(char_length(reproduction_steps)>0),CHECK(char_length(expected_result)>0),CHECK(char_length(actual_result)>0),CHECK(requirement_id IS NOT NULL OR task_id IS NOT NULL OR test_case_id IS NOT NULL OR test_run_id IS NOT NULL),CHECK((status IN ('resolved','verified','closed') AND resolution<>'' AND char_length(resolution_note)>0) OR (status NOT IN ('resolved','verified','closed') AND resolution='' AND resolution_note='')),CHECK((deleted_at=0 AND deleted_by=0) OR (deleted_at>0 AND deleted_by>0)),
 CONSTRAINT fk_workspace_defect_requirement FOREIGN KEY(requirement_id) REFERENCES workspace_requirements(id) ON DELETE RESTRICT,CONSTRAINT fk_workspace_defect_task FOREIGN KEY(task_id) REFERENCES workspace_tasks(id) ON DELETE RESTRICT,CONSTRAINT fk_workspace_defect_case FOREIGN KEY(test_case_id) REFERENCES workspace_test_cases(id) ON DELETE RESTRICT,CONSTRAINT fk_workspace_defect_run FOREIGN KEY(test_run_id) REFERENCES workspace_test_runs(id) ON DELETE RESTRICT,
 INDEX idx_workspace_defects_scope(tenant_id,entity_id,deleted_at,status,severity,updated_at),INDEX idx_workspace_defects_sources(tenant_id,entity_id,requirement_id,task_id,test_case_id,test_run_id,deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- +goose Down
DROP TABLE IF EXISTS workspace_defects;
